### ISSUE TITLE
2.3.5version wireguardCannot be used normally

### ISSUE THREAD

**Issue by seagullz4** [MHSanaei/3x-ui#2421] opened 2024-06-18 08:41 UTC
**Describe the bug**

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
 - 3X-UI Version : [e.g. 2.3.5]
 - Xray Version : [e.g. 1.8.13]

**Additional context**

2.3.5version wireguardCannot be used normallyIncluding the 2.3.4 version will not work, but 2.3.3 can use wireguard，Hope to fix this bug soon

**Comment by alireza0** [comment] 2024-06-18 09:38
It is not a bug in x-ui/3x-ui panels and was only a bug in xray-core.
Please read other issues and then create new one.
Today you can find the problem fixed by new release of xray-core: 1.8.15

**Closed** 2024-06-23 22:47 UTC
Labels: bug
