### ISSUE TITLE
 مشکل عدم پایداری اینستا - اگر راه حلی دارید لطفا بگید امتحان کنم  

### ISSUE THREAD

**Issue by smj1234** [MHSanaei/3x-ui#1495] opened 2024-01-01 15:34 UTC
سلام قضیه اینه که داخل ریلز اینستا یدفعه قطع میشه - بعد میرم تلگرام و .. میبینم وصله 
اسپید تست میگیرم سرعت بالاست . جیتر پایین پینگ پااین - روی همه لوکیشنا هم همینه 

 حالا اگر تو همین اینستا برم روی پستا یا توی اکسپلور لود میکنه :///// - صرفا مشکل با ریلزه 

بعد مثلا چند ثانیه دوباره وصل میشه ممکنه حتی تا 30 ثانیه طول بکشه - هرچی روش به ذهنم رسیده رو رفتم نمیدونم دقیقا مشکل از کجاست که پیگیری کنم 

کسی راه حلی داره ؟

**Comment by lvlehr4d** [comment] 2024-01-02 09:05
warp رو راه اندازی کن تست کن ببین اگه اینستا رو بندازی روی وارپ اوکی میشه

**Comment by smj1234** [comment] 2024-01-02 10:47
> warp رو راه اندازی کن تست کن ببین اگه اینستا رو بندازی روی وارپ اوکی میشه

متاسفانه تست کردم قبلا مشکل حل نشده - مشکل از ایپی نیست که بخام با وارپ حلش کنم

**Comment by sharif221** [comment] 2024-01-02 10:48
this is helpful #1317

**Comment by smj1234** [comment] 2024-01-02 13:16
> this is helpful #1317

سلام متشکرم متاسفانه این راه حل بستن پاکت ها به علت کپسوله شدن رو مسائلی کاربرد داره که شما بریا مثال بعضی از پست ها لود نمیشه - داخل اکسپلور که حرکت میکنید یک تعداد پست لود نشده سیاه وحود داره (با توجه به حالت شب یا روز ممکنه سفید باشه)

و اینکه اینم تست کرده بودم تاثیری ندشات - تعیید پیشفرض MTU  هم تاثیر بسزایی نمیزاره متاسفانه 

چون که منشا مشکل مشخض نیست نمیتونم راه حلی پیدا کنم براش 

و خوب در رابطه با راع حلی که فرمودید باید توجه داشته باشید که این روش ممکنه وری توییتر اختلال ایجاد کنه

**Comment by smj1234** [comment] 2024-01-02 13:17
و اینکه عذر میخام بابت غلط املایی :)) چندتا کارو باهم دارم انجام میدم

**Comment by sharif221** [comment] 2024-01-04 17:39
the problem comes from using the QUIC protocol which is primary in some apps like Instagram, YouTube, or Twitter.
by blocking this protocol the app (like Instagram servers) is forced not to use this protocol, I should note that vmess/vless is all TCP means any UDP connection is converted to TCP and then sent to the client so this comes with some penalty, like not loading as fast or have one or 2 images black in Instagram explore. but most of the problem is QUIC.

you can also change the rules is the Sanai panel a little bit. for example block UDP 443 on geosite:Instagram or geosite:google, this action makes sure that this rule does not mess up Twitter or others.

but at first you should make sure your v2ray work fine and not suffer from low speed of filtering.

**Comment by smj1234** [comment] 2024-01-04 18:48
> the problem comes from using the QUIC protocol which is primary in some apps like Instagram, YouTube, or Twitter. by blocking this protocol the app (like Instagram servers) is forced not to use this protocol, I should note that vmess/vless is all TCP means any UDP connection is converted to TCP and then sent to the client so this comes with some penalty, like not loading as fast or have one or 2 images black in Instagram explore. but most of the problem is QUIC.
> 
> you can also change the rules is the Sanai panel a little bit. for example block UDP 443 on geosite:Instagram or geosite:google, this action makes sure that this rule does not mess up Twitter or others.
> 
> but at first you should make sure your v2ray work fine and not suffer from low speed of filtering.

thx for wise advice - considering you as a not native in our language will reply in yours instead- also apologize for any misusing the words or et ... | 

 i should say that this is good idea to use the Geosits data for Instagram to prevent the problems on twitter - there is no such thing as a low speed or filter on my servers its dynamic and the speed test at the exact moment of  tied problem was actually fine with low jitter (less than 5') low ping (less than 100) and even high speed (less than 10% loss from Real Str8 connection) - once i tried to block QUIC but didn't help much 

 i tried to change protocols from Vless/Vmess to shadow socks or even trojan but  ended up in same result -
 even i played with mtu ,i did guess that it might have problem  with distribution of  the packages or problems like that but ended up the same situation - 
now i have no idea wat is the problem even tried Warp or changing Ips it didn't Worked unfortunately 

i will try to only restrict all udp packages on YouTube and Instagram and i will update the result here | hope it will work

**Comment by sharif221** [comment] 2024-01-04 19:27
Thanks,

I should mention that its fine if in Instagram explore 13 out of 16 images load but final 3 images load with around 0.3 second delay its the penalty of using xudp (tcp over udp) instead of actual udp.

Its not something that can be fixed in v2ray, but with different network connections its possible to not see any difference at all in day to day use.

The other thing that can be considered is MUX, its a client side toggle that make connection more efficient and you can decide maximum xudp connections, most likely using 8 or 16 is optimal in Iran.

Other thing is making sure server not using ipv6 for Instagram (Instagram servers don't like ipv6), most servers comes with ipv4 and ipv6 in same time. You can also edit this in routing rules in xray setting specifically for Instagram if you have ipv6 assigned to server.

**Comment by smj1234** [comment] 2024-01-04 20:09
> Thanks,
> 
> I should mention that its fine if in Instagram explore 13 out of 16 images load but final 3 images load with around 0.3 second delay its the penalty of using xudp (tcp over udp) instead of actual udp.
> 
> Its not something that can be fixed in v2ray, but with different network connections its possible to not see any difference at all in day to day use.
> 
> The other thing that can be considered is MUX, its a client side toggle that make connection more efficient and you can decide maximum xudp connections, most likely using 8 or 16 is optimal in Iran.
> 
> Other thing is making sure server not using ipv6 for Instagram (Instagram servers don't like ipv6), most servers comes with ipv4 and ipv6 in same time. You can also edit this in routing rules in Xray setting specifically for Instagram if you have ipv6 assigned to server.

Hello ty - I used the routing for insta so it wont use ipv6 - I tried mux but had negative effect on YouTube and telegram is tehre anything that i can do to prevent this ? i tried to change is from 2 to 16 and with the increment the result get worst!

I don't think its a delay its looks like the connection problem or something like that !  all the post and reels in explore works just fine but if you go on one reel and then usen sweep after while you will face the lag and  - 

also should mention in that turning off and on the vpn app will solve the problem  - in this case  I'm using auto reestablish connections every 2h on servers but didn't saw difference

**Comment by smj1234** [comment] 2024-01-05 10:28
resolving process update : I recently tried to change every setting in the configs and i got something but still i can find teh reason behind it - i might face same problem in future with this solution also - more time is needed  to , validate 

with removing the headers from configs the problems mostly solved - i should mention that i still have some problems in twitter such as delay in loading pics ... Quick in not blocked on twitter ( assumed that therouting works well but unfortunately i faced lots of problems with xcore routing - its really weak )

now that i have found root  i can explore it and find the reason behind it - it might came from the MTU , i did check and change the MTU from 1280 to 1500 - even i put exact numerical result (TCP + HEADER + 2IP + Core encryption) but had no result before i will dig deeper this time 


آپدیت برای رفع مشکل : با توجه به پیشنهاداتی که اراسل شده بنده کلا یدور 0 تا 100 سرور رو تغییر دادم هم برای مستقیم و هم برای تانل و نتیجه ای که پیدا کردم این بوده که مشکل رو هدر ایجاد میکنه
اما همچنان منطق پشتتشو درک نکرده ممکنه از سمت ماکس ترانسپورت باشه اما خوب الان که حدودی ریشه مشکل اینستاگرامو استخراج کردم میتونم کامل بررسی کنم و سعی و خطا انجام بدم و دلیل و راه حل اگر پیدا کردم همینجا میگم


مشکل دیلی روی تویتتر همچنان باقی هست بدون پیدا شدن ریشه

**Comment by sharif221** [comment] 2024-01-06 07:30
Oh! I should asked about what config do you use :/

The problem with (tcp + http + request header) is that its so easy for iran to spot and make it less viable.
First: it doesn't use TLS.
Second: has different quality in different Hours, its so unstable during peak internet usage.


Thay can't completely ban this config but it's in the weakest time in past 3 month.

I recommend using ws tls with cloudflair.
This can help you: https://github.com/rahgozar94725/freedom/

**Comment by smj1234** [comment] 2024-01-06 07:32
> Oh! I should asked about what config do you use :/
> 
> The problem with (tcp + http + request header) is that its so easy for iran to spot and make it less viable. First: it doesn't use TLS. Second: has different quality in different Hours, its so unstable during peak internet usage.
> 
> Thay can't completely ban this config but it's in the weakest time in past 3 month.
> 
> I recommend using ws tls with cloudflair. This can help you: https://github.com/rahgozar94725/freedom/

i mostly use  VL/VM   TCP/WS + (HTTP HEADER + TLS)

**Closed** 2024-06-23 22:52 UTC
Labels: question
